export default function ThermalReportLayout({

  title,

  children

}) {

  return (

    <div className="
      thermal-report
      bg-white
      text-black
    ">

      {/* HEADER */}
      <div className="
        thermal-center
      ">

        <h2 className="
          thermal-bold
        ">

          Restaurant POS

        </h2>

        <div className="
          thermal-small
        ">

          {title}

        </div>

        <div className="
          thermal-small
        ">

          {new Date()
            .toLocaleString()}

        </div>

      </div>

      <div className="
        thermal-divider
      " />

      {/* CONTENT */}
      {children}

      <div className="
        thermal-divider
      " />

      {/* FOOTER */}
      <div className="
        thermal-center
        thermal-small
      ">

        Generated by
        Restaurant ERP

      </div>

    </div>

  );
}